### ISSUE TITLE
jobmon runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by Barbers** [cloudradar-monitoring/cagent#246]
I try to move my backup cron to jobmon, but it raises an error.
Now it wrotes me that a job with the same id is allready running.

command:
`jobmon -id backup -re=false -s none -- pg_dumpall > ~/postgres/backups/$(date +%F).bak`

output:
```
panic: runtime error: slice bounds out of range

goroutine 17 [running]:
github.com/cloudradar-monitoring/cagent/pkg/jobmon.(*captureWriter).Write(0xc0001b4090, 0xc0001d8000, 0x1000, 0x8000, 0x1000, 0x0, 0x0)
        /go/src/github.com/cloudradar-monitoring/cagent/pkg/jobmon/writer.go:25 +0x2aa
io.copyBuffer(0x7e63a0, 0xc0001b4090, 0x7e6800, 0xc0001a2108, 0xc0001d8000, 0x8000, 0x8000, 0x0, 0x0, 0x1000000000001)
        /usr/local/go/src/io/io.go:404 +0x1fb
io.Copy(...)
        /usr/local/go/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0xc00001c360, 0x0)
        /usr/local/go/src/os/exec/exec.go:288 +0x63
os/exec.(*Cmd).Start.func1(0xc0001ae000, 0xc00019c2c0)
        /usr/local/go/src/os/exec/exec.go:409 +0x27
created by os/exec.(*Cmd).Start
        /usr/local/go/src/os/exec/exec.go:408 +0x58f
```

**Comment by nikita-vanyasin** [comment]
Hi @Barbers 
The fix will be available in next stable release (1.3.8).
If you want to check out the fix ASAP, you can use [1.3.7-rc1](https://github.com/cloudradar-monitoring/cagent/releases/tag/1.3.7-rc1).
